#!/bin/zsh

APPNAME="Quake3"
PACKAGENAME= Quake3

(cd $OMNI_SOURCE_ROOT; ./Build Quake3 install)

rm -rf "/tmp/$APPNAME"
mkdir "/tmp/$APPNAME"
cp "Read Me.rtf" "/tmp/$APPNAME"

cd /Users/Shared/$USER/InstalledProducts
gnutar cf - FAKK2.app | (cd "/tmp/$APPNAME"; gnutar xf -)

cd "/tmp/$APPNAME"
sudo ~bungi/Unix/bin/files2image $PACKAGENAME ./*

